---
title: "Matthew Flanagan's Dissertation: Descriptive Stats"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}

library(psych)
library(dplyr)

```

```{r}
# Sample Descriptive by role
describe.by(joined,joined$role)
table(joined$role)

# Professional Role Frequency Table
table(joined$ProfRole)

#Youth demographics
table(joined$youthRace)
table(joined$youthAge)
table(joined$youthGender)
table(joined$youthAgeF)
table(joined$youthGenderF)
table(joined$youthRaceF)

```

```{r}
# Scale reliability----

# subset - YOUTH
SQIOnly <- joined %>% select(c(s1.1,s1.2,s1.3,s1.4,
                                   s2.1,s2.2,s2.3,s2.4,s2.5,s2.6,s2.7,s2.8,
                                   s3.1,s3.1,
                                   s4.1,s4.2,s4.3,s4.4,
                                   s5.1,s5.2,s5.3,s5.4,
                                   s6.1,s6.2,s6.3,s6.4,s6.5,s6.6,s6.7,s6.8,
                                   s7.1,s7.2,s7.3,s7.4,s7.5,s7.6,s7.7,
                                   s8.1,s8.2,s8.3,s8.4,s8.5,s8.6,s8.6,s8.7,s8.8,s8.9,s8.10,s8.11,s8.12,s8.13,
                                   s9.1,s9.2,s9.3,s9.4))

SQIOnlyYouth <- joined %>% filter (role == "I'm a Young Person")

SQIOnlyYouth <- SQIOnlyYouth %>% select(c(S1.1Y,S1.2Y,S1.3Y,S1.4Y,
                                    S2.1Y,S2.2Y,S2.3Y,S2.4Y,S2.5Y,S2.6Y,S2.7Y,S2.8Y,
                                    S3.1Y,S3.2Y,
                                    S4.1Y,S4.2Y,S4.3Y,S4.4Y,
                                    S5.1Y,S5.2Y,S5.3Y,S5.4Y,
                                    S6.1Y,S6.2Y,S6.3Y,S6.4Y,S6.5Y,S6.6Y,S6.7Y,S6.8Y,
                                    S7.1Y,S7.2Y,S7.3Y,S7.4Y,S7.5Y,S7.6Y,S7.7Y,
                                    S8.1Y,S8.2Y,S8.3Y,S8.4Y,S8.5Y,S8.6Y,
                                    S8.7Y,S8.8Y,S8.9Y,S8.10Y,S8.11Y,S8.12Y,S8.13Y,
                                    S9.1Y,S9.2Y,S9.3Y,S9.4Y))

SQI1Youth <- SQIOnlyYouth %>% select(c(S1.1Y,S1.2Y,S1.3Y,S1.4Y))
SQI2Youth <- SQIOnlyYouth %>% select(c(S2.1Y,S2.2Y,S2.3Y,S2.4Y,S2.5Y,S2.6Y,S2.7Y,S2.8Y))
SQI3Youth <- SQIOnlyYouth %>% select(c(S3.1Y,S3.2Y))
SQI4Youth <- SQIOnlyYouth %>% select(c(S4.1Y,S4.2Y,S4.3Y,S4.4Y))
SQI5Youth <- SQIOnlyYouth %>% select(c(S5.1Y,S5.2Y,S5.3Y,S5.4Y))
SQI6Youth <- SQIOnlyYouth %>% select(c(S6.1Y,S6.2Y,S6.3Y,S6.4Y,S6.5Y,S6.6Y,S6.7Y,S6.8Y))
SQI7Youth <- SQIOnlyYouth %>% select(c(S7.1Y,S7.2Y,S7.3Y,S7.4Y,S7.5Y,S7.6Y,S7.7Y))
SQI8Youth <- SQIOnlyYouth %>% select(c(S8.1Y,S8.2Y,S8.3Y,S8.4Y,S8.5Y,S8.6Y,
                                    S8.7Y,S8.8Y,S8.9Y,S8.10Y,S8.11Y,S8.12Y,S8.13Y))
SQI9Youth <- SQIOnlyYouth %>% select(c(S9.1Y,S9.2Y,S9.3Y,S9.4Y))



alpha(SQIOnlyYouth,na.rm=TRUE)
alpha(SQI1Youth,na.rm=TRUE)
alpha(SQI2Youth,na.rm=TRUE)
alpha(SQI3Youth,na.rm=TRUE)
alpha(SQI4Youth,na.rm=TRUE)
alpha(SQI5Youth,na.rm=TRUE)
alpha(SQI6Youth,na.rm=TRUE)
alpha(SQI7Youth,na.rm=TRUE)
alpha(SQI8Youth,na.rm=TRUE)
alpha(SQI9Youth,na.rm=TRUE)

mean(SQI1Youth$S1.1Y + SQI1Youth$S1.2Y + SQI1Youth$S1.3Y + SQI1Youth$S1.4Y, na.rm = TRUE)
sd(SQI1Youth$S1.1Y + SQI1Youth$S1.2Y + SQI1Youth$S1.3Y + SQI1Youth$S1.4Y, na.rm = TRUE)

mean(SQI2Youth$S2.1Y + SQI2Youth$S2.2Y + SQI2Youth$S2.3Y + SQI2Youth$S2.4Y + SQI2Youth$S2.5Y + SQI2Youth$S2.6Y + SQI2Youth$S2.7Y + SQI2Youth$S2.8Y, na.rm = TRUE)
sd(SQI2Youth$S2.1Y + SQI2Youth$S2.2Y + SQI2Youth$S2.3Y + SQI2Youth$S2.4Y + SQI2Youth$S2.5Y + SQI2Youth$S2.6Y + SQI2Youth$S2.7Y + SQI2Youth$S2.8Y, na.rm = TRUE)

mean(SQI3Youth$S3.1Y + SQI3Youth$S3.2Y, na.rm = TRUE)
sd(SQI3Youth$S3.1Y + SQI3Youth$S3.2Y, na.rm = TRUE)

mean(SQI4Youth$S4.1Y + SQI4Youth$S4.2Y + SQI4Youth$S4.3Y + SQI4Youth$S4.4Y, na.rm = TRUE)
sd(SQI4Youth$S4.1Y + SQI4Youth$S4.2Y + SQI4Youth$S4.3Y + SQI4Youth$S4.4Y, na.rm = TRUE)

mean(SQI5Youth$S5.1Y + SQI5Youth$S5.2Y + SQI5Youth$S5.3Y + SQI5Youth$S5.4Y, na.rm = TRUE)
sd(SQI5Youth$S5.1Y + SQI5Youth$S5.2Y + SQI5Youth$S5.3Y + SQI5Youth$S5.4Y, na.rm = TRUE)

mean(SQI6Youth$S6.1Y + SQI6Youth$S6.2Y + SQI6Youth$S6.3Y + SQI6Youth$S6.4Y + SQI6Youth$S6.5Y + SQI6Youth$S6.6Y + SQI6Youth$S6.7Y + SQI6Youth$S6.8Y, na.rm = TRUE)
sd(SQI6Youth$S6.1Y + SQI6Youth$S6.2Y + SQI6Youth$S6.3Y + SQI6Youth$S6.4Y + SQI6Youth$S6.5Y + SQI6Youth$S6.6Y + SQI6Youth$S6.7Y + SQI6Youth$S6.8Y, na.rm = TRUE)

mean(SQI7Youth$S7.1Y + SQI7Youth$S7.2Y + SQI7Youth$S7.3Y + SQI7Youth$S7.4Y + SQI7Youth$S7.5Y + SQI7Youth$S7.6Y + SQI7Youth$S7.7Y, na.rm = TRUE)
sd(SQI7Youth$S7.1Y + SQI7Youth$S7.2Y + SQI7Youth$S7.3Y + SQI7Youth$S7.4Y + SQI7Youth$S7.5Y + SQI7Youth$S7.6Y + SQI7Youth$S7.7Y, na.rm = TRUE)

mean(SQI8Youth$S8.1Y + SQI8Youth$S8.2Y + SQI8Youth$S8.3Y + SQI8Youth$S8.4Y + SQI8Youth$S8.5Y + SQI8Youth$S8.6Y + SQI8Youth$S8.7Y + SQI8Youth$S8.8Y + SQI8Youth$S8.9Y + SQI8Youth$S8.10Y + SQI8Youth$S8.11Y + SQI8Youth$S8.12Y + SQI8Youth$S8.13Y, na.rm = TRUE)

sd(SQI8Youth$S8.1Y + SQI8Youth$S8.2Y + SQI8Youth$S8.3Y + SQI8Youth$S8.4Y + SQI8Youth$S8.5Y + SQI8Youth$S8.6Y + SQI8Youth$S8.7Y + SQI8Youth$S8.8Y + SQI8Youth$S8.9Y + SQI8Youth$S8.10Y + SQI8Youth$S8.11Y + SQI8Youth$S8.12Y + SQI8Youth$S8.13Y, na.rm = TRUE)

mean(SQI9Youth$S9.1Y + SQI9Youth$S9.2Y + SQI9Youth$S9.3Y + SQI9Youth$S9.4Y, na.rm = TRUE)
sd(SQI9Youth$S9.1Y + SQI9Youth$S9.2Y + SQI9Youth$S9.3Y + SQI9Youth$S9.4Y, na.rm = TRUE)

# subset - family

SQIOnlyFAM <- joined %>% filter (role == "I'm a Parent / Legal Guardian")

SQIOnlyFAM <- SQIOnlyFAM %>% select(c(S1.1F,S1.2F,S1.3F,S1.4F,
                                    S2.1F,S2.2F,S2.3F,S2.4F,S2.5F,S2.6F,S2.7F,S2.8F,
                                    S3.1F,S3.2F,
                                    S4.1F,S4.2F,S4.3F,S4.4F,
                                    S5.1F,S5.2F,S5.3F,S5.4F,
                                    S6.1F,S6.2F,S6.3F,S6.4F,S6.5F,S6.6F,S6.7F,S6.8F,
                                    S7.1F,S7.2F,S7.3F,S7.4F,S7.5F,S7.6F,S7.7F,
                                    S8.1F,S8.2F,S8.3F,S8.4F,S8.5F,S8.6F,
                                    S8.7F,S8.8F,S8.9F,S8.10F,S8.11F,S8.12F,S8.13F,
                                    S9.1F,S9.2F,S9.3F,S9.4F))

SQI1FAM <- SQIOnlyFAM %>% select(c(S1.1F,S1.2F,S1.3F,S1.4F))
SQI2FAM <- SQIOnlyFAM %>% select(c(S2.1F,S2.2F,S2.3F,S2.4F,S2.5F,S2.6F,S2.7F,S2.8F))
SQI3FAM <- SQIOnlyFAM %>% select(c(S3.1F,S3.2F))
SQI4FAM <- SQIOnlyFAM %>% select(c(S4.1F,S4.2F,S4.3F,S4.4F))
SQI5FAM <- SQIOnlyFAM %>% select(c(S5.1F,S5.2F,S5.3F,S5.4F))
SQI6FAM <- SQIOnlyFAM %>% select(c(S6.1F,S6.2F,S6.3F,S6.4F,S6.5F,S6.6F,S6.7F,S6.8F))
SQI7FAM <- SQIOnlyFAM %>% select(c(S7.1F,S7.2F,S7.3F,S7.4F,S7.5F,S7.6F,S7.7F))
SQI8FAM <- SQIOnlyFAM %>% select(c(S8.1F,S8.2F,S8.3F,S8.4F,S8.5F,S8.6F,S8.7F,S8.8F,S8.9F,S8.10F,S8.11F,S8.12F,S8.13F))
SQI9FAM <- SQIOnlyFAM %>% select(c(S9.1F,S9.2F,S9.3F,S9.4F))

alpha(SQIOnlyFAM,na.rm=TRUE)
alpha(SQI1FAM,na.rm=TRUE)
alpha(SQI2FAM,na.rm=TRUE)
alpha(SQI3FAM,na.rm=TRUE)
alpha(SQI4FAM,na.rm=TRUE)
alpha(SQI5FAM,na.rm=TRUE)
alpha(SQI6FAM,na.rm=TRUE)
alpha(SQI7FAM,na.rm=TRUE)
alpha(SQI8FAM,na.rm=TRUE)
alpha(SQI9FAM,na.rm=TRUE)

mean(SQI1FAM$S1.1F + SQI1FAM$S1.2F + SQI1FAM$S1.3F + SQI1FAM$S1.4F, na.rm = TRUE)
sd(SQI1FAM$S1.1F + SQI1FAM$S1.2F + SQI1FAM$S1.3F + SQI1FAM$S1.4F, na.rm = TRUE)

mean(SQI2FAM$S2.1F + SQI2FAM$S2.2F + SQI2FAM$S2.3F + SQI2FAM$S2.4F + SQI2FAM$S2.5F + SQI2FAM$S2.6F + SQI2FAM$S2.7F + SQI2FAM$S2.8F, na.rm = TRUE)
sd(SQI2FAM$S2.1F + SQI2FAM$S2.2F + SQI2FAM$S2.3F + SQI2FAM$S2.4F + SQI2FAM$S2.5F + SQI2FAM$S2.6F + SQI2FAM$S2.7F + SQI2FAM$S2.8F, na.rm = TRUE)

mean(SQI3FAM$S3.1F + SQI3FAM$S3.2F, na.rm = TRUE)
sd(SQI3FAM$S3.1F + SQI3FAM$S3.2F, na.rm = TRUE)

mean(SQI4FAM$S4.1F + SQI4FAM$S4.2F + SQI4FAM$S4.3F + SQI4FAM$S4.4F, na.rm = TRUE)
sd(SQI4FAM$S4.1F + SQI4FAM$S4.2F + SQI4FAM$S4.3F + SQI4FAM$S4.4F, na.rm = TRUE)

mean(SQI5FAM$S5.1F + SQI5FAM$S5.2F + SQI5FAM$S5.3F + SQI5FAM$S5.4F, na.rm = TRUE)
sd(SQI5FAM$S5.1F + SQI5FAM$S5.2F + SQI5FAM$S5.3F + SQI5FAM$S5.4F, na.rm = TRUE)

mean(SQI6FAM$S6.1F + SQI6FAM$S6.2F + SQI6FAM$S6.3F + SQI6FAM$S6.4F + SQI6FAM$S6.5F + SQI6FAM$S6.6F + SQI6FAM$S6.7F + SQI6FAM$S6.8F, na.rm = TRUE)
sd(SQI6FAM$S6.1F + SQI6FAM$S6.2F + SQI6FAM$S6.3F + SQI6FAM$S6.4F + SQI6FAM$S6.5F + SQI6FAM$S6.6F + SQI6FAM$S6.7F + SQI6FAM$S6.8F, na.rm = TRUE)

mean(SQI7FAM$S7.1F + SQI7FAM$S7.2F + SQI7FAM$S7.3F + SQI7FAM$S7.4F + SQI7FAM$S7.5F + SQI7FAM$S7.6F + SQI7FAM$S7.7F, na.rm = TRUE)
sd(SQI7FAM$S7.1F + SQI7FAM$S7.2F + SQI7FAM$S7.3F + SQI7FAM$S7.4F + SQI7FAM$S7.5F + SQI7FAM$S7.6F + SQI7FAM$S7.7F, na.rm = TRUE)

mean(SQI8FAM$S8.1F + SQI8FAM$S8.2F + SQI8FAM$S8.3F + SQI8FAM$S8.4F + SQI8FAM$S8.5F + SQI8FAM$S8.6F + SQI8FAM$S8.7F + SQI8FAM$S8.8F + SQI8FAM$S8.9F + SQI8FAM$S8.10F + SQI8FAM$S8.11F + SQI8FAM$S8.12F + SQI8FAM$S8.13F, na.rm = TRUE)

sd(SQI8FAM$S8.1F + SQI8FAM$S8.2F + SQI8FAM$S8.3F + SQI8FAM$S8.4F + SQI8FAM$S8.5F + SQI8FAM$S8.6F + SQI8FAM$S8.7F + SQI8FAM$S8.8F + SQI8FAM$S8.9F + SQI8FAM$S8.10F + SQI8FAM$S8.11F + SQI8FAM$S8.12F + SQI8FAM$S8.13F, na.rm = TRUE)

mean(SQI9FAM$S9.1F + SQI9FAM$S9.2F + SQI9FAM$S9.3F + SQI9FAM$S9.4F, na.rm = TRUE)
sd(SQI9FAM$S9.1F + SQI9FAM$S9.2F + SQI9FAM$S9.3F + SQI9FAM$S9.4F, na.rm = TRUE)


# subset - stakeholder

SQIOnlySTK <- joined %>% filter (role == "I'm a Transition Stakeholder")

SQIOnlySTK <- SQIOnlySTK %>% select(c(S1.1S,S1.2S,S1.3S,S1.4S,
                                    S2.1S,S2.2S,S2.3S,S2.4S,S2.5S,S2.6S,S2.7S,S2.8S,
                                    S3.1S,S3.2S,
                                    S4.1S,S4.2S,S4.3S,S4.4S,
                                    S5.1S,S5.2S,S5.3S,S5.4S,
                                    S6.1S,S6.2S,S6.3S,S6.4S,S6.5S,S6.6S,S6.7S,S6.8S,
                                    S7.1S,S7.2S,S7.3S,S7.4S,S7.5S,S7.6S,S7.7S,
                                    S8.1S,S8.2S,S8.3S,S8.4S,S8.5S,S8.6S,
                                    S8.7S,S8.8S,S8.9S,S8.10S,S8.11S,S8.12S,S8.13S,
                                    S9.1S,S9.2S,S9.3S,S9.4S))

SQI1STK <- SQIOnlySTK %>% select(c(S1.1S,S1.2S,S1.3S,S1.4S))
SQI2STK <- SQIOnlySTK %>% select(c(S2.1S,S2.2S,S2.3S,S2.4S,S2.5S,S2.6S,S2.7S,S2.8S))
SQI3STK <- SQIOnlySTK %>% select(c(S3.1S,S3.2S))
SQI4STK <- SQIOnlySTK %>% select(c(S4.1S,S4.2S,S4.3S,S4.4S))
SQI5STK <- SQIOnlySTK %>% select(c(S5.1S,S5.2S,S5.3S,S5.4S))
SQI6STK <- SQIOnlySTK %>% select(c(S6.1S,S6.2S,S6.3S,S6.4S,S6.5S,S6.6S,S6.7S,S6.8S))
SQI7STK <- SQIOnlySTK %>% select(c(S7.1S,S7.2S,S7.3S,S7.4S,S7.5S,S7.6S,S7.7S))
SQI8STK <- SQIOnlySTK %>% select(c(S8.1S,S8.2S,S8.3S,S8.4S,S8.5S,S8.6S,S8.7S,S8.8S,S8.9S,S8.10S,S8.11S,S8.12S,S8.13S))
SQI9STK <- SQIOnlySTK %>% select(c(S9.1S,S9.2S,S9.3S,S9.4S))

alpha(SQIOnlySTK,na.rm=TRUE)
alpha(SQI1STK,na.rm=TRUE)
alpha(SQI2STK,na.rm=TRUE)
alpha(SQI3STK,na.rm=TRUE)
alpha(SQI4STK,na.rm=TRUE)
alpha(SQI5STK,na.rm=TRUE)
alpha(SQI6STK,na.rm=TRUE)
alpha(SQI7STK,na.rm=TRUE)
alpha(SQI8STK,na.rm=TRUE)
alpha(SQI9STK,na.rm=TRUE)

mean(SQI1STK$S1.1S + SQI1STK$S1.2S + SQI1STK$S1.3S + SQI1STK$S1.4S, na.rm = TRUE)
sd(SQI1STK$S1.1S + SQI1STK$S1.2S + SQI1STK$S1.3S + SQI1STK$S1.4S, na.rm = TRUE)

mean(SQI2STK$S2.1S + SQI2STK$S2.2S + SQI2STK$S2.3S + SQI2STK$S2.4S + SQI2STK$S2.5S + SQI2STK$S2.6S + SQI2STK$S2.7S + SQI2STK$S2.8S, na.rm = TRUE)
sd(SQI2STK$S2.1S + SQI2STK$S2.2S + SQI2STK$S2.3S + SQI2STK$S2.4S + SQI2STK$S2.5S + SQI2STK$S2.6S + SQI2STK$S2.7S + SQI2STK$S2.8S, na.rm = TRUE)

mean(SQI3STK$S3.1S + SQI3STK$S3.2S, na.rm = TRUE)
sd(SQI3STK$S3.1S + SQI3STK$S3.2S, na.rm = TRUE)

mean(SQI4STK$S4.1S + SQI4STK$S4.2S + SQI4STK$S4.3S + SQI4STK$S4.4S, na.rm = TRUE)
sd(SQI4STK$S4.1S + SQI4STK$S4.2S + SQI4STK$S4.3S + SQI4STK$S4.4S, na.rm = TRUE)

mean(SQI5STK$S5.1S + SQI5STK$S5.2S + SQI5STK$S5.3S + SQI5STK$S5.4S, na.rm = TRUE)
sd(SQI5STK$S5.1S + SQI5STK$S5.2S + SQI5STK$S5.3S + SQI5STK$S5.4S, na.rm = TRUE)

mean(SQI6STK$S6.1S + SQI6STK$S6.2S + SQI6STK$S6.3S + SQI6STK$S6.4S + SQI6STK$S6.5S + SQI6STK$S6.6S + SQI6STK$S6.7S + SQI6STK$S6.8S, na.rm = TRUE)
sd(SQI6STK$S6.1S + SQI6STK$S6.2S + SQI6STK$S6.3S + SQI6STK$S6.4S + SQI6STK$S6.5S + SQI6STK$S6.6S + SQI6STK$S6.7S + SQI6STK$S6.8S, na.rm = TRUE)

mean(SQI7STK$S7.1S + SQI7STK$S7.2S + SQI7STK$S7.3S + SQI7STK$S7.4S + SQI7STK$S7.5S + SQI7STK$S7.6S + SQI7STK$S7.7S, na.rm = TRUE)
sd(SQI7STK$S7.1S + SQI7STK$S7.2S + SQI7STK$S7.3S + SQI7STK$S7.4S + SQI7STK$S7.5S + SQI7STK$S7.6S + SQI7STK$S7.7S, na.rm = TRUE)

mean(SQI8STK$S8.1S + SQI8STK$S8.2S + SQI8STK$S8.3S + SQI8STK$S8.4S + SQI8STK$S8.5S + SQI8STK$S8.6S + SQI8STK$S8.7S + SQI8STK$S8.8S + SQI8STK$S8.9S + SQI8STK$S8.10S + SQI8STK$S8.11S + SQI8STK$S8.12S + SQI8STK$S8.13S, na.rm = TRUE)

sd(SQI8STK$S8.1S + SQI8STK$S8.2S + SQI8STK$S8.3S + SQI8STK$S8.4S + SQI8STK$S8.5S + SQI8STK$S8.6S + SQI8STK$S8.7S + SQI8STK$S8.8S + SQI8STK$S8.9S + SQI8STK$S8.10S + SQI8STK$S8.11S + SQI8STK$S8.12S + SQI8STK$S8.13S, na.rm = TRUE)

mean(SQI9STK$S9.1S + SQI9STK$S9.2S + SQI9STK$S9.3S + SQI9STK$S9.4S, na.rm = TRUE)
sd(SQI9STK$S9.1S + SQI9STK$S9.2S + SQI9STK$S9.3S + SQI9STK$S9.4S, na.rm = TRUE)


```