---
title: "Matthew Flanagan's Dissertation: Data Cleaning"
output: html_notebook
---

```{R}
# Load all packages
library(tidyverse)
library(readxl)

```

```{R}
# Import data - COHORT I & II

Abington_C2 <- read_excel("Abington.xlsx")
Agora_C2 <- read_excel("Agora.xlsx")
Allentown_C1 <- read_excel("Allentown.xlsx")
AvonGrove_C1 <- read_excel("Avon_Grove.xlsx")
Bethel_C2 <- read_excel("Bethel.xlsx")
Butler_C1 <- read_excel("Butler.xlsx")
CannonMac_C1 <- read_excel("Canon_McMillan.xlsx")
CommonwealthCyberC2 <- read_excel("Commonwealth.xlsx")
Curwensville_C2 <- read_excel("Curwensville.xlsx")
Dover_C2 <- read_excel("Dover.xlsx")
EastLycoming_C1 <- read_excel("East_Lycoming.xlsx")
HillFreedman_C2 <- read_excel("HillFreedman.xlsx")
InsightPA_C2 <- read_excel("InsightPa.xlsx")
Lebanon_C2 <- read_excel("Lebanon.xlsx")
Maritime_C2 <- read_excel("Maritime.xlsx")
Moshannon_C2 <- read_excel("Moshannon.xlsx")
MountainView_C1 <- read_excel("Mountain_View.xlsx")
PaVirtual_C1 <- read_excel("PA_Virtual_Charter.xlsx")
PleasantValley_C2 <- read_excel("Pleasant.xlsx")
Plum_C1 <- read_excel("Plum_Borough.xlsx")
ReachCyber_C2 <- read_excel("ReachCyber.xlsx")
SoutheastDelco_C1 <- read_excel("Southeast_Delco.xlsx")
Southpark_C2 <- read_excel("SouthPark.xlsx")
SouthWestern_C1 <- read_excel("SouthWestern.xlsx")
Troy_C2 <- read_excel("Troy.xlsx")
UnionArea_C1 <- read_excel("Union_Area.xlsx")

# list of c1 dfs for non-charters. Will iterate through it and clean each.
C1_Dfs_NonCharter <- list("Allentown" = Allentown_C1,
                          "AvonGrove" = AvonGrove_C1,
                          "Bulter" = Butler_C1,
                          "CannonMac" = CannonMac_C1,
                          "EastLycoming" = EastLycoming_C1,
                          "MountainView" = MountainView_C1,
                          "Plum" = Plum_C1,
                          "SouthEastDelco" = SoutheastDelco_C1,
                          "SouthWestern" = SouthWestern_C1,
                          "UnionArea" = UnionArea_C1)

C2_Dfs <- list("Abington" = Abington_C2,
               "Agora" = Agora_C2,
               "Bethel" = Bethel_C2,
               "Curwensville" = Curwensville_C2,
               "Commonwealth" = CommonwealthCyberC2,
               "Dover" = Dover_C2,
               "Lebanon" = Lebanon_C2,
               "Moshannon" = Moshannon_C2,
               "PleasantValley" = PleasantValley_C2,
               "SouthPark" = Southpark_C2,
               "Troy" = Troy_C2,
               "HillFreedman" = HillFreedman_C2,
               "InsightPA" = InsightPA_C2,
               "Maritime" = Maritime_C2,
               "Reach" = ReachCyber_C2)

# C2_Dfs_Charter <- list("Agora" = Agora_C2,
#                        "HillFreedman" = HillFreedman_C2,
#                        "InsightPA" = InsightPA_C2,
#                        "Maritime" = Maritime_C2,
#                        "Reach" = ReachCyber_C2
#                        )

```

```{r}
# CLEAN CHORT I SITES----------

# remove unneeded columns
C1_Dfs_NonCharter <- map(C1_Dfs_NonCharter, ~(.x %>%
  
select(-c(StartDate,EndDate,Status,Progress,`Duration (in seconds)`,Finished,RecordedDate,DistributionChannel,UserLanguage,Q5,Q5_38_TEXT,Q6,Q6_7_TEXT,Q7,Q8,Q65_9_TEXT,Q65_10_TEXT,Q68,Q68_64_TEXT,Q656,Q657,Q658,Q671,Q672,Q673,Q680,Q681,Q682,Q691,Q692,Q693,Q702,Q703,Q704,Q717,Q718,Q719,Q731,Q732,Q733,Q751,Q752,Q752,Q753,Q762,Q763,Q764,Q674,Q674_17_TEXT,Q674_18_TEXT,Q165,Q177,Q178,Q179,Q189,Q190,Q191,Q195,Q196,Q197,Q203,Q204,Q205,Q211,Q212,Q213,Q223,Q224,Q225,Q234,Q235,Q236,Q251,Q252,Q253,Q259,Q260,Q261,Q262,Q263,Q166,Q164_10_TEXT,Q170_1,Q170_2,Q170_3,Q170_4,Q170_5,Q171_1,Q171_4,Q171_5,Q171_6,Q171_7,Q560_1,Q560_2,Q560_3,Q560_4,Q560_5,Q561,Q562,Q655,Q670,Q679,Q690,Q701,Q716,Q730,Q750,Q761,Q827,Q828,321:698,703:715)) 

))

# remove first row that has secondary header junk from Qualtrics
C1_Dfs_NonCharter <- map(C1_Dfs_NonCharter, ~(.x %>%
                                                filter(!row_number() %in% c(1))
                                              )
                         )

forReferenceC1 <- C1_Dfs_NonCharter[["Allentown"]]

C1_Dfs_NonCharter <- map(C1_Dfs_NonCharter, ~(.x %>%
                                                rename(
                                                  role = Q1,
                                                  # YOUTH
                                                  youthAge = Q2,
                                                  youthGender = Q3,
                                                  youthRace = Q4,
                                                  S1.1Y = Q773,
                                                  S1.2Y = Q774,
                                                  S1.3Y = Q775,
                                                  S1.4Y = Q776,
                                                  S2.1Y = Q777,
                                                  S2.2Y = Q778,
                                                  S2.3Y = Q779,
                                                  S2.4Y = Q780,
                                                  S2.5Y = Q781,
                                                  S2.6Y = Q782,
                                                  S2.7Y = Q783,
                                                  S2.8Y = Q784,
                                                  S3.1Y = Q785,
                                                  S3.2Y = Q786,
                                                  S4.1Y = Q787,
                                                  S4.2Y = Q788,
                                                  S4.3Y = Q789,
                                                  S4.4Y = Q790,
                                                  S5.1Y = Q791,
                                                  S5.2Y = Q792,
                                                  S5.3Y = Q793,
                                                  S5.4Y = Q794,
                                                  S6.1Y = Q795,
                                                  S6.2Y = Q796,
                                                  S6.3Y = Q797,
                                                  S6.4Y = Q798,
                                                  S6.5Y = Q799,
                                                  S6.6Y = Q800,
                                                  S6.7Y = Q801,
                                                  S6.8Y = Q802,
                                                  S7.1Y = Q803,
                                                  S7.2Y = Q804,
                                                  S7.3Y = Q805,
                                                  S7.4Y = Q806,
                                                  S7.5Y = Q807,
                                                  S7.6Y = Q808,
                                                  S7.7Y = Q809,
                                                  S8.1Y = Q810,
                                                  S8.2Y = Q811,
                                                  S8.3Y = Q812,
                                                  S8.4Y = Q813,
                                                  S8.5Y = Q814,
                                                  S8.6Y = Q815,
                                                  S8.7Y = Q816,
                                                  S8.8Y = Q817,
                                                  S8.9Y = Q818,
                                                  S8.10Y = Q819,
                                                  S8.11Y = Q820,
                                                  S8.12Y = Q821,
                                                  S8.13Y = Q822,
                                                  S9.1Y = Q823,
                                                  S9.2Y = Q824,
                                                  S9.3Y = Q825,
                                                  S9.4Y = Q826,
                                                  # STAKEHOLDERS
                                                  ProfRole = Q65,
                                                  ProfAgeRangeS = Q67,
                                                  S1.1S = Q649,
                                                  S1.2S = Q650,
                                                  S1.3S = Q651,
                                                  S1.4S = Q652,
                                                  Q1ADAPT1 = Q653_1,
                                                  Q1ADAPT2 = Q653_2,
                                                  Q1ADAPT3 = Q653_3,
                                                  Q1ACCESS1 = Q654_1,
                                                  Q1ACCESS2 = Q654_2,
                                                  Q1ACCESS3 = Q654_3,
                                                  S2.1S = Q660,
                                                  S2.2S = Q661,
                                                  S2.3S = Q662,
                                                  S2.4S = Q663,
                                                  S2.5S = Q664,
                                                  S2.6S = Q665,
                                                  S2.7S = Q666,
                                                  S2.8S = Q667,
                                                  Q2ADAPT1 = Q668_1,
                                                  Q2ADAPT2 = Q668_2,
                                                  Q2ADAPT3 = Q668_3,
                                                  Q2ACCESS1 = Q669_1,
                                                  Q2ACCESS2 = Q669_2,
                                                  Q2ACCESS3 = Q669_3,
                                                  S3.1S = Q675,
                                                  S3.2S = Q676,
                                                  Q3ADAPT1 = Q677_1,
                                                  Q3ADAPT2 = Q677_2,
                                                  Q3ADAPT3 = Q677_3,
                                                  Q3ACCESS1 = Q678_1,
                                                  Q3ACCESS2 = Q678_2,
                                                  Q3ACCESS3 = Q678_3,
                                                  S4.1S = Q684,
                                                  S4.2S = Q685,
                                                  S4.3S = Q686,
                                                  S4.4S = Q687,
                                                  Q4ADAPT1 = Q688_1,
                                                  Q4ADAPT2 = Q688_2,
                                                  Q4ADAPT3 = Q688_3,
                                                  Q4ACCESS1 = Q689_1,
                                                  Q4ACCESS2 = Q689_2,
                                                  Q4ACCESS3 = Q689_3,
                                                  S5.1S = Q695,
                                                  S5.2S = Q696,
                                                  S5.3S = Q697,
                                                  S5.4S = Q698,
                                                  Q5ADAPT1 = Q699_1,
                                                  Q5ADAPT2 = Q699_2,
                                                  Q5ADAPT3 = Q699_3,
                                                  Q5ACCESS1 = Q700_1,
                                                  Q5ACCESS2 = Q700_2,
                                                  Q5ACCESS3 = Q700_3,
                                                  S6.1S = Q706,
                                                  S6.2S = Q707,
                                                  S6.3S = Q708,
                                                  S6.4S = Q709,
                                                  S6.5S = Q710,
                                                  S6.6S = Q711,
                                                  S6.7S = Q712,
                                                  S6.8S = Q713,
                                                  Q6ADAPT1 = Q714_1,
                                                  Q6ADAPT2 = Q714_2,
                                                  Q6ADAPT3 = Q714_3,
                                                  Q6ACCESS1 = Q715_1,
                                                  Q6ACCESS2 = Q715_2,
                                                  Q6ACCESS3 = Q715_3,
                                                  S7.1S = Q721,
                                                  S7.2S = Q722,
                                                  S7.3S = Q723,
                                                  S7.4S = Q724,
                                                  S7.5S = Q725,
                                                  S7.6S = Q726,
                                                  S7.7S = Q727,
                                                  Q7ADAPT1 = Q728_1,
                                                  Q7ADAPT2 = Q728_2,
                                                  Q7ADAPT3 = Q728_3,
                                                  Q7ACCESS1 = Q729_1,
                                                  Q7ACCESS2 = Q729_2,
                                                  Q7ACCESS3 = Q729_3,
                                                  S8.1S = Q735,
                                                  S8.2S = Q736,
                                                  S8.3S = Q737,
                                                  S8.4S = Q738,
                                                  S8.5S = Q739,
                                                  S8.6S = Q740,
                                                  S8.7S = Q741,
                                                  S8.8S = Q742,
                                                  S8.9S = Q743,
                                                  S8.10S = Q744,
                                                  S8.11S = Q745,
                                                  S8.12S = Q746,
                                                  S8.13S = Q747,
                                                  Q8ADAPT1 = Q748_1,
                                                  Q8ADAPT2 = Q748_2,
                                                  Q8ADAPT3 = Q748_3,
                                                  Q8ACCESS1 = Q749_1,
                                                  Q8ACCESS2 = Q749_2,
                                                  Q8ACCESS3 = Q749_3,
                                                  S9.1S = Q755,
                                                  S9.2S = Q756,
                                                  S9.3S = Q757,
                                                  S9.4S = Q758,
                                                  Q9ADAPT1 = Q759_1,
                                                  Q9ADAPT2 = Q759_2,
                                                  Q9ADAPT3 = Q759_3,
                                                  Q9ACCESS1 = Q760_1,
                                                  Q9ACCESS2 = Q760_2,
                                                  Q9ACCESS3 = Q760_3,
                                                  #FAMILIES
                                                  youthAgeF = Q161,
                                                  youthGenderF = Q162,
                                                  youthRaceF = Q163,
                                                  S1.1F = Q173,
                                                  S1.2F = Q174,
                                                  S1.3F = Q175,
                                                  S1.4F = Q176,
                                                  S2.1F = Q181,
                                                  S2.2F = Q182,
                                                  S2.3F = Q183,
                                                  S2.4F = Q184,
                                                  S2.5F = Q185,
                                                  S2.6F = Q186,
                                                  S2.7F = Q187,
                                                  S2.8F = Q188,
                                                  S3.1F = Q193,
                                                  S3.2F = Q194,
                                                  S4.1F = Q199,
                                                  S4.2F = Q200,
                                                  S4.3F = Q201,
                                                  S4.4F = Q202,
                                                  S5.1F = Q207,
                                                  S5.2F = Q208,
                                                  S5.3F = Q209,
                                                  S5.4F = Q210,
                                                  S6.1F = Q215,
                                                  S6.2F = Q216,
                                                  S6.3F = Q217,
                                                  S6.4F = Q218,
                                                  S6.5F = Q219,
                                                  S6.6F = Q220,
                                                  S6.7F = Q221,
                                                  S6.8F = Q222,
                                                  S7.1F = Q227,
                                                  S7.2F = Q228,
                                                  S7.3F = Q229,
                                                  S7.4F = Q230,
                                                  S7.5F = Q231,
                                                  S7.6F = Q232,
                                                  S7.7F = Q233,
                                                  S8.1F = Q238,
                                                  S8.2F = Q239,
                                                  S8.3F = Q240,
                                                  S8.4F = Q241,
                                                  S8.5F = Q242,
                                                  S8.6F = Q243,
                                                  S8.7F = Q244,
                                                  S8.8F = Q245,
                                                  S8.9F = Q246,
                                                  S8.10F = Q247,
                                                  S8.11F = Q248,
                                                  S8.12F = Q249,
                                                  S8.13F = Q250,
                                                  S9.1F = Q255,
                                                  S9.2F = Q256,
                                                  S9.3F = Q257,
                                                  S9.4F = Q258                                                  
                                                )
                                              )
)

#only keep needed columns
C1_Dfs_NonCharter <- map(C1_Dfs_NonCharter, ~(.x %>%
                                                select(c(
                                                  role,
                                                  youthAge,
                                                  youthGender,
                                                  youthRace,
                                                  S1.1Y,
                                                  S1.2Y,
                                                  S1.3Y,
                                                  S1.4Y,
                                                  S2.1Y,
                                                  S2.2Y,
                                                  S2.3Y,
                                                  S2.4Y,
                                                  S2.5Y,
                                                  S2.6Y,
                                                  S2.7Y,
                                                  S2.8Y,
                                                  S3.1Y,
                                                  S3.2Y,
                                                  S4.1Y,
                                                  S4.2Y,
                                                  S4.3Y,
                                                  S4.4Y,
                                                  S5.1Y,
                                                  S5.2Y,
                                                  S5.3Y,
                                                  S5.4Y,
                                                  S6.1Y,
                                                  S6.2Y,
                                                  S6.3Y,
                                                  S6.4Y,
                                                  S6.5Y,
                                                  S6.6Y,
                                                  S6.7Y,
                                                  S6.8Y,
                                                  S7.1Y,
                                                  S7.2Y,
                                                  S7.3Y,
                                                  S7.4Y,
                                                  S7.5Y,
                                                  S7.6Y,
                                                  S7.7Y,
                                                  S8.1Y,
                                                  S8.2Y,
                                                  S8.3Y,
                                                  S8.4Y,
                                                  S8.5Y,
                                                  S8.6Y,
                                                  S8.7Y,
                                                  S8.8Y,
                                                  S8.9Y,
                                                  S8.10Y,
                                                  S8.11Y,
                                                  S8.12Y,
                                                  S8.13Y,
                                                  S9.1Y,
                                                  S9.2Y,
                                                  S9.3Y,
                                                  S9.4Y,
                                                  ProfRole,
                                                  ProfAgeRangeS,
                                                  S1.1S,
                                                  S1.2S,
                                                  S1.3S,
                                                  S1.4S,
                                                  Q1ADAPT1,
                                                  Q1ADAPT2,
                                                  Q1ADAPT3,
                                                  Q1ACCESS1,
                                                  Q1ACCESS2,
                                                  Q1ACCESS3,
                                                  S2.1S,
                                                  S2.2S,
                                                  S2.3S,
                                                  S2.4S,
                                                  S2.5S,
                                                  S2.6S,
                                                  S2.7S,
                                                  S2.8S,
                                                  Q2ADAPT1,
                                                  Q2ADAPT2,
                                                  Q2ADAPT3,
                                                  Q2ACCESS1,
                                                  Q2ACCESS2,
                                                  Q2ACCESS3,
                                                  S3.1S,
                                                  S3.2S,
                                                  Q3ADAPT1,
                                                  Q3ADAPT2,
                                                  Q3ADAPT3,
                                                  Q3ACCESS1,
                                                  Q3ACCESS2,
                                                  Q3ACCESS3,
                                                  S4.1S,
                                                  S4.2S,
                                                  S4.3S,
                                                  S4.4S,
                                                  Q4ADAPT1,
                                                  Q4ADAPT2,
                                                  Q4ADAPT3,
                                                  Q4ACCESS1,
                                                  Q4ACCESS2,
                                                  Q4ACCESS3,
                                                  S5.1S,
                                                  S5.2S,
                                                  S5.3S,
                                                  S5.4S,
                                                  Q5ADAPT1,
                                                  Q5ADAPT2,
                                                  Q5ADAPT3,
                                                  Q5ACCESS1,
                                                  Q5ACCESS2,
                                                  Q5ACCESS3,
                                                  S6.1S,
                                                  S6.2S,
                                                  S6.3S,
                                                  S6.4S,
                                                  S6.5S,
                                                  S6.6S,
                                                  S6.7S,
                                                  S6.8S,
                                                  Q6ADAPT1,
                                                  Q6ADAPT2,
                                                  Q6ADAPT3,
                                                  Q6ACCESS1,
                                                  Q6ACCESS2,
                                                  Q6ACCESS3,
                                                  S7.1S,
                                                  S7.2S,
                                                  S7.3S,
                                                  S7.4S,
                                                  S7.5S,
                                                  S7.6S,
                                                  S7.7S,
                                                  Q7ADAPT1,
                                                  Q7ADAPT2,
                                                  Q7ADAPT3,
                                                  Q7ACCESS1,
                                                  Q7ACCESS2,
                                                  Q7ACCESS3,
                                                  S8.1S,
                                                  S8.2S,
                                                  S8.3S,
                                                  S8.4S,
                                                  S8.5S,
                                                  S8.6S,
                                                  S8.7S,
                                                  S8.8S,
                                                  S8.9S,
                                                  S8.10S,
                                                  S8.11S,
                                                  S8.12S,
                                                  S8.13S,
                                                  Q8ADAPT1,
                                                  Q8ADAPT2,
                                                  Q8ADAPT3,
                                                  Q8ACCESS1,
                                                  Q8ACCESS2,
                                                  Q8ACCESS3,
                                                  S9.1S,
                                                  S9.2S,
                                                  S9.3S,
                                                  S9.4S,
                                                  Q9ADAPT1,
                                                  Q9ADAPT2,
                                                  Q9ADAPT3,
                                                  Q9ACCESS1,
                                                  Q9ACCESS2,
                                                  Q9ACCESS3,
                                                  youthAgeF,
                                                  youthGenderF,
                                                  youthRaceF,
                                                  S1.1F,
                                                  S1.2F,
                                                  S1.3F,
                                                  S1.4F,
                                                  S2.1F,
                                                  S2.2F,
                                                  S2.3F,
                                                  S2.4F,
                                                  S2.5F,
                                                  S2.6F,
                                                  S2.7F,
                                                  S2.8F,
                                                  S3.1F,
                                                  S3.2F,
                                                  S4.1F,
                                                  S4.2F,
                                                  S4.3F,
                                                  S4.4F,
                                                  S5.1F,
                                                  S5.2F,
                                                  S5.3F,
                                                  S5.4F,
                                                  S6.1F,
                                                  S6.2F,
                                                  S6.3F,
                                                  S6.4F,
                                                  S6.5F,
                                                  S6.6F,
                                                  S6.7F,
                                                  S6.8F,
                                                  S7.1F,
                                                  S7.2F,
                                                  S7.3F,
                                                  S7.4F,
                                                  S7.5F,
                                                  S7.6F,
                                                  S7.7F,
                                                  S8.1F,
                                                  S8.2F,
                                                  S8.3F,
                                                  S8.4F,
                                                  S8.5F,
                                                  S8.6F,
                                                  S8.7F,
                                                  S8.8F,
                                                  S8.9F,
                                                  S8.10F,
                                                  S8.11F,
                                                  S8.12F,
                                                  S8.13F,
                                                  S9.1F,
                                                  S9.2F,
                                                  S9.3F,
                                                  S9.4F                                                  
                                                ))
))



# # clean C1 Charter (because of diff question numbers)
# PaVirtual_C1 <- PaVirtual_C1 %>% select(-c(1:10,15:18,73,74,76,77,91:93,109:111,121:123,135:137,149:151,167:169,184:186,207:209,221:223,224,228:231,236:238,247:249,252:254:259:261,266:268,277:279,287:289,303:305,310:314,315:706,709:720))
```

```{r}
# CLEAN COHORT II SITES-----------

C2_Dfs <- map(C2_Dfs, ~(.x %>% rename(Duration = 'Duration (in seconds)')))

# remove first row that has secondary header junk from Qualtrics
C2_Dfs <- map(C2_Dfs, ~(.x %>% filter(!row_number() %in% c(1))))

C2_Dfs <- map(C2_Dfs, ~(.x %>%
                          rename(
                            role = Q1,
                            # YOUTH
                            youthAge = Q2,
                            youthGender = Q3,
                            youthRace = Q4,
                            S1.1Y = Q773,
                            S1.2Y = Q774,
                            S1.3Y = Q775,
                            S1.4Y = Q776,
                            S2.1Y = Q777,
                            S2.2Y = Q778,
                            S2.3Y = Q779,
                            S2.4Y = Q780,
                            S2.5Y = Q781,
                            S2.6Y = Q782,
                            S2.7Y = Q783,
                            S2.8Y = Q784,
                            S3.1Y = Q785,
                            S3.2Y = Q786,
                            S4.1Y = Q787,
                            S4.2Y = Q788,
                            S4.3Y = Q789,
                            S4.4Y = Q790,
                            S5.1Y = Q791,
                            S5.2Y = Q792,
                            S5.3Y = Q793,
                            S5.4Y = Q794,
                            S6.1Y = Q795,
                            S6.2Y = Q796,
                            S6.3Y = Q797,
                            S6.4Y = Q798,
                            S6.5Y = Q799,
                            S6.6Y = Q800,
                            S6.7Y = Q801,
                            S6.8Y = Q802,
                            S7.1Y = Q803,
                            S7.2Y = Q804,
                            S7.3Y = Q805,
                            S7.4Y = Q806,
                            S7.5Y = Q807,
                            S7.6Y = Q808,
                            S7.7Y = Q809,
                            S8.1Y = Q810,
                            S8.2Y = Q811,
                            S8.3Y = Q812,
                            S8.4Y = Q813,
                            S8.5Y = Q814,
                            S8.6Y = Q815,
                            S8.7Y = Q816,
                            S8.8Y = Q817,
                            S8.9Y = Q818,
                            S8.10Y = Q819,
                            S8.11Y = Q820,
                            S8.12Y = Q821,
                            S8.13Y = Q822,
                            S9.1Y = Q823,
                            S9.2Y = Q824,
                            S9.3Y = Q825,
                            S9.4Y = Q826,
                            # STAKEHOLDERS
                            ProfRole = Q65,
                            ProfAgeRangeS = Q67,
                            S1.1S = Q649,
                            S1.2S = Q650,
                            S1.3S = Q651,
                            S1.4S = Q652,
                            Q1ADAPT1 = Q653_1,
                            Q1ADAPT2 = Q653_2,
                            Q1ADAPT3 = Q653_3,
                            Q1ACCESS1 = Q654_1,
                            Q1ACCESS2 = Q654_2,
                            Q1ACCESS3 = Q654_3,
                            S2.1S = Q660,
                            S2.2S = Q661,
                            S2.3S = Q662,
                            S2.4S = Q663,
                            S2.5S = Q664,
                            S2.6S = Q665,
                            S2.7S = Q666,
                            S2.8S = Q667,
                            Q2ADAPT1 = Q668_1,
                            Q2ADAPT2 = Q668_2,
                            Q2ADAPT3 = Q668_3,
                            Q2ACCESS1 = Q669_1,
                            Q2ACCESS2 = Q669_2,
                            Q2ACCESS3 = Q669_3,
                            S3.1S = Q675,
                            S3.2S = Q676,
                            Q3ADAPT1 = Q677_1,
                            Q3ADAPT2 = Q677_2,
                            Q3ADAPT3 = Q677_3,
                            Q3ACCESS1 = Q678_1,
                            Q3ACCESS2 = Q678_2,
                            Q3ACCESS3 = Q678_3,
                            S4.1S = Q684,
                            S4.2S = Q685,
                            S4.3S = Q686,
                            S4.4S = Q687,
                            Q4ADAPT1 = Q688_1,
                            Q4ADAPT2 = Q688_2,
                            Q4ADAPT3 = Q688_3,
                            Q4ACCESS1 = Q689_1,
                            Q4ACCESS2 = Q689_2,
                            Q4ACCESS3 = Q689_3,
                            S5.1S = Q695,
                            S5.2S = Q696,
                            S5.3S = Q697,
                            S5.4S = Q698,
                            Q5ADAPT1 = Q699_1,
                            Q5ADAPT2 = Q699_2,
                            Q5ADAPT3 = Q699_3,
                            Q5ACCESS1 = Q700_1,
                            Q5ACCESS2 = Q700_2,
                            Q5ACCESS3 = Q700_3,
                            S6.1S = Q706,
                            S6.2S = Q707,
                            S6.3S = Q708,
                            S6.4S = Q709,
                            S6.5S = Q710,
                            S6.6S = Q711,
                            S6.7S = Q712,
                            S6.8S = Q713,
                            Q6ADAPT1 = Q714_1,
                            Q6ADAPT2 = Q714_2,
                            Q6ADAPT3 = Q714_3,
                            Q6ACCESS1 = Q715_1,
                            Q6ACCESS2 = Q715_2,
                            Q6ACCESS3 = Q715_3,
                            S7.1S = Q721,
                            S7.2S = Q722,
                            S7.3S = Q723,
                            S7.4S = Q724,
                            S7.5S = Q725,
                            S7.6S = Q726,
                            S7.7S = Q727,
                            Q7ADAPT1 = Q728_1,
                            Q7ADAPT2 = Q728_2,
                            Q7ADAPT3 = Q728_3,
                            Q7ACCESS1 = Q729_1,
                            Q7ACCESS2 = Q729_2,
                            Q7ACCESS3 = Q729_3,
                            S8.1S = Q735,
                            S8.2S = Q736,
                            S8.3S = Q737,
                            S8.4S = Q738,
                            S8.5S = Q739,
                            S8.6S = Q740,
                            S8.7S = Q741,
                            S8.8S = Q742,
                            S8.9S = Q743,
                            S8.10S = Q744,
                            S8.11S = Q745,
                            S8.12S = Q746,
                            S8.13S = Q747,
                            Q8ADAPT1 = Q748_1,
                            Q8ADAPT2 = Q748_2,
                            Q8ADAPT3 = Q748_3,
                            Q8ACCESS1 = Q749_1,
                            Q8ACCESS2 = Q749_2,
                            Q8ACCESS3 = Q749_3,
                            S9.1S = Q755,
                            S9.2S = Q756,
                            S9.3S = Q757,
                            S9.4S = Q758,
                            Q9ADAPT1 = Q759_1,
                            Q9ADAPT2 = Q759_2,
                            Q9ADAPT3 = Q759_3,
                            Q9ACCESS1 = Q760_1,
                            Q9ACCESS2 = Q760_2,
                            Q9ACCESS3 = Q760_3,
                            #FAMILIES
                            youthAgeF = Q161,
                            youthGenderF = Q162,
                            youthRaceF = Q163,
                            S1.1F = Q173,
                            S1.2F = Q174,
                            S1.3F = Q175,
                            S1.4F = Q176,
                            S2.1F = Q181,
                            S2.2F = Q182,
                            S2.3F = Q183,
                            S2.4F = Q184,
                            S2.5F = Q185,
                            S2.6F = Q186,
                            S2.7F = Q187,
                            S2.8F = Q188,
                            S3.1F = Q193,
                            S3.2F = Q194,
                            S4.1F = Q199,
                            S4.2F = Q200,
                            S4.3F = Q201,
                            S4.4F = Q202,
                            S5.1F = Q207,
                            S5.2F = Q208,
                            S5.3F = Q209,
                            S5.4F = Q210,
                            S6.1F = Q215,
                            S6.2F = Q216,
                            S6.3F = Q217,
                            S6.4F = Q218,
                            S6.5F = Q219,
                            S6.6F = Q220,
                            S6.7F = Q221,
                            S6.8F = Q222,
                            S7.1F = Q227,
                            S7.2F = Q228,
                            S7.3F = Q229,
                            S7.4F = Q230,
                            S7.5F = Q231,
                            S7.6F = Q232,
                            S7.7F = Q233,
                            S8.1F = Q238,
                            S8.2F = Q239,
                            S8.3F = Q240,
                            S8.4F = Q241,
                            S8.5F = Q242,
                            S8.6F = Q243,
                            S8.7F = Q244,
                            S8.8F = Q245,
                            S8.9F = Q246,
                            S8.10F = Q247,
                            S8.11F = Q248,
                            S8.12F = Q249,
                            S8.13F = Q250,
                            S9.1F = Q255,
                            S9.2F = Q256,
                            S9.3F = Q257,
                            S9.4F = Q258
                          )
                        )
)

#only keep needed columns
C2_Dfs <- map(C2_Dfs, ~(.x %>%
                          select(c(
                            role,
                            youthAge,
                            youthGender,
                            youthRace,
                            S1.1Y,
                            S1.2Y,
                            S1.3Y,
                            S1.4Y,
                            S2.1Y,
                            S2.2Y,
                            S2.3Y,
                            S2.4Y,
                            S2.5Y,
                            S2.6Y,
                            S2.7Y,
                            S2.8Y,
                            S3.1Y,
                            S3.2Y,
                            S4.1Y,
                            S4.2Y,
                            S4.3Y,
                            S4.4Y,
                            S5.1Y,
                            S5.2Y,
                            S5.3Y,
                            S5.4Y,
                            S6.1Y,
                            S6.2Y,
                            S6.3Y,
                            S6.4Y,
                            S6.5Y,
                            S6.6Y,
                            S6.7Y,
                            S6.8Y,
                            S7.1Y,
                            S7.2Y,
                            S7.3Y,
                            S7.4Y,
                            S7.5Y,
                            S7.6Y,
                            S7.7Y,
                            S8.1Y,
                            S8.2Y,
                            S8.3Y,
                            S8.4Y,
                            S8.5Y,
                            S8.6Y,
                            S8.7Y,
                            S8.8Y,
                            S8.9Y,
                            S8.10Y,
                            S8.11Y,
                            S8.12Y,
                            S8.13Y,
                            S9.1Y,
                            S9.2Y,
                            S9.3Y,
                            S9.4Y,
                            ProfRole,
                            ProfAgeRangeS,
                            S1.1S,
                            S1.2S,
                            S1.3S,
                            S1.4S,
                            Q1ADAPT1,
                            Q1ADAPT2,
                            Q1ADAPT3,
                            Q1ACCESS1,
                            Q1ACCESS2,
                            Q1ACCESS3,
                            S2.1S,
                            S2.2S,
                            S2.3S,
                            S2.4S,
                            S2.5S,
                            S2.6S,
                            S2.7S,
                            S2.8S,
                            Q2ADAPT1,
                            Q2ADAPT2,
                            Q2ADAPT3,
                            Q2ACCESS1,
                            Q2ACCESS2,
                            Q2ACCESS3,
                            S3.1S,
                            S3.2S,
                            Q3ADAPT1,
                            Q3ADAPT2,
                            Q3ADAPT3,
                            Q3ACCESS1,
                            Q3ACCESS2,
                            Q3ACCESS3,
                            S4.1S,
                            S4.2S,
                            S4.3S,
                            S4.4S,
                            Q4ADAPT1,
                            Q4ADAPT2,
                            Q4ADAPT3,
                            Q4ACCESS1,
                            Q4ACCESS2,
                            Q4ACCESS3,
                            S5.1S,
                            S5.2S,
                            S5.3S,
                            S5.4S,
                            Q5ADAPT1,
                            Q5ADAPT2,
                            Q5ADAPT3,
                            Q5ACCESS1,
                            Q5ACCESS2,
                            Q5ACCESS3,
                            S6.1S,
                            S6.2S,
                            S6.3S,
                            S6.4S,
                            S6.5S,
                            S6.6S,
                            S6.7S,
                            S6.8S,
                            Q6ADAPT1,
                            Q6ADAPT2,
                            Q6ADAPT3,
                            Q6ACCESS1,
                            Q6ACCESS2,
                            Q6ACCESS3,
                            S7.1S,
                            S7.2S,
                            S7.3S,
                            S7.4S,
                            S7.5S,
                            S7.6S,
                            S7.7S,
                            Q7ADAPT1,
                            Q7ADAPT2,
                            Q7ADAPT3,
                            Q7ACCESS1,
                            Q7ACCESS2,
                            Q7ACCESS3,
                            S8.1S,
                            S8.2S,
                            S8.3S,
                            S8.4S,
                            S8.5S,
                            S8.6S,
                            S8.7S,
                            S8.8S,
                            S8.9S,
                            S8.10S,
                            S8.11S,
                            S8.12S,
                            S8.13S,
                            Q8ADAPT1,
                            Q8ADAPT2,
                            Q8ADAPT3,
                            Q8ACCESS1,
                            Q8ACCESS2,
                            Q8ACCESS3,
                            S9.1S,
                            S9.2S,
                            S9.3S,
                            S9.4S,
                            Q9ADAPT1,
                            Q9ADAPT2,
                            Q9ADAPT3,
                            Q9ACCESS1,
                            Q9ACCESS2,
                            Q9ACCESS3,
                            youthAgeF,
                            youthGenderF,
                            youthRaceF,
                            S1.1F,
                            S1.2F,
                            S1.3F,
                            S1.4F,
                            S2.1F,
                            S2.2F,
                            S2.3F,
                            S2.4F,
                            S2.5F,
                            S2.6F,
                            S2.7F,
                            S2.8F,
                            S3.1F,
                            S3.2F,
                            S4.1F,
                            S4.2F,
                            S4.3F,
                            S4.4F,
                            S5.1F,
                            S5.2F,
                            S5.3F,
                            S5.4F,
                            S6.1F,
                            S6.2F,
                            S6.3F,
                            S6.4F,
                            S6.5F,
                            S6.6F,
                            S6.7F,
                            S6.8F,
                            S7.1F,
                            S7.2F,
                            S7.3F,
                            S7.4F,
                            S7.5F,
                            S7.6F,
                            S7.7F,
                            S8.1F,
                            S8.2F,
                            S8.3F,
                            S8.4F,
                            S8.5F,
                            S8.6F,
                            S8.7F,
                            S8.8F,
                            S8.9F,
                            S8.10F,
                            S8.11F,
                            S8.12F,
                            S8.13F,
                            S9.1F,
                            S9.2F,
                            S9.3F,
                            S9.4F
                          ))
))

```

```{r}
#remove unneeded dfs
rm(Abington_C2,Agora_C2,Allentown_C1,AvonGrove_C1,Bethel_C2,Butler_C1,CannonMac_C1,Curwensville_C2,Dover_C2,EastLycoming_C1,HillFreedman_C2,InsightPA_C2,Lebanon_C2,Maritime_C2,Moshannon_C2,MountainView_C1,PaVirtual_C1,PleasantValley_C2,Plum_C1,ReachCyber_C2,SoutheastDelco_C1,Southpark_C2,SouthWestern_C1,Troy_C2,UnionArea_C1,forReferenceC1,CommonwealthCyberC2)

```

```{R}
#join dataframes

Allentown_C1 <- C1_Dfs_NonCharter$Allentown
AvonGrove_C1 <- C1_Dfs_NonCharter$AvonGrove
Butler_C1 <- C1_Dfs_NonCharter$Bulter
CannonMac_C1 <- C1_Dfs_NonCharter$CannonMac
EastLycoming_C1 <- C1_Dfs_NonCharter$EastLycoming
MountainView_C1 <- C1_Dfs_NonCharter$MountainView
Plum_C1 <- C1_Dfs_NonCharter$Plum
SoutheastDelco_C1 <- C1_Dfs_NonCharter$SouthEastDelco
SouthWestern_C1 <- C1_Dfs_NonCharter$SouthWestern
UnionArea_C1 <- C1_Dfs_NonCharter$UnionArea
Abington_C2 <- C2_Dfs$Abington
Agora_C2 <- C2_Dfs$Agora
Bethel_C2 <- C2_Dfs$Bethel
Curwensville_C2 <- C2_Dfs$Curwensville
CommonwealthCyberC2 <- C2_Dfs$Commonwealth
Dover_C2 <- C2_Dfs$Dover
HillFreedman_C2 <- C2_Dfs$HillFreedman
InsightPA_C2 <- C2_Dfs$InsightPA
Maritime_C2 <- C2_Dfs$Maritime
Moshannon_C2 <- C2_Dfs$Moshannon
PleasantValley_C2 <- C2_Dfs$PleasantValley
ReachCyber_C2 <- C2_Dfs$Reach
Southpark_C2 <- C2_Dfs$SouthPark
Troy_C2 <- C2_Dfs$Troy

Allentown_C1$LEA <- "Allentown"
AvonGrove_C1$LEA <- "AvonGrove"
Butler_C1$LEA <- "Butler"
CannonMac_C1$LEA <- "CannonMac"
EastLycoming_C1$LEA <- "EastLycoming"
MountainView_C1$LEA <- "MountainView"
Plum_C1$LEA <- "Plum"
SoutheastDelco_C1$LEA <- "SeDelco"
SouthWestern_C1$LEA <- "Southwestern"
UnionArea_C1$LEA <- "UnionArea"
Abington_C2$LEA <- "Abington"
Agora_C2$LEA <- "Agora"
Bethel_C2$LEA <- "Bethel"
Curwensville_C2$LEA <- "Curwensville"
CommonwealthCyberC2$LEA <- "Commonwealth"
Dover_C2$LEA <- "Dover"
HillFreedman_C2$LEA <- "HillFreedman"
InsightPA_C2$LEA <- "InsightPA"
Maritime_C2$LEA <- "Maritime"
Moshannon_C2$LEA <- "Moshannon"
PleasantValley_C2$LEA <- "PleasantValley"
ReachCyber_C2$LEA <- "Reach"
Southpark_C2$LEA <- "Southpark"
Troy_C2$LEA <- "Troy"

joined <- full_join(Allentown_C1,AvonGrove_C1)
joined <- full_join(joined,Butler_C1)
joined <- full_join(joined,CannonMac_C1)
joined <- full_join(joined,EastLycoming_C1)
joined <- full_join(joined,MountainView_C1)
joined <- full_join(joined,Plum_C1)
joined <- full_join(joined,SoutheastDelco_C1)
joined <- full_join(joined,SouthWestern_C1)
joined <- full_join(joined,UnionArea_C1)
joined <- full_join(joined,Abington_C2)
joined <- full_join(joined,Agora_C2)
joined <- full_join(joined,Bethel_C2)
joined <- full_join(joined,Curwensville_C2)
joined <- full_join(joined,CommonwealthCyberC2)
joined <- full_join(joined,Dover_C2)
joined <- full_join(joined,HillFreedman_C2)
joined <- full_join(joined,InsightPA_C2)
joined <- full_join(joined,Maritime_C2)
joined <- full_join(joined,Moshannon_C2)
joined <- full_join(joined,PleasantValley_C2)
joined <- full_join(joined,ReachCyber_C2)
joined <- full_join(joined,Southpark_C2)
joined <- full_join(joined,Troy_C2)

joined <- joined %>% mutate_at(vars(5:59), #re-code youth ratings
            ~as.numeric(recode(.x,
              "A lot"=4,
              "Some"=3,
              "Not at all"=2,
              "Don't Know / Doesn't Relate to Me" = NULL,
            )))

joined <- joined %>% mutate_at(vars(61:64,71:78,85,86,93:96,103:106,113:120,127:133,140:152,159:162), #re-code stk ratings
            ~as.numeric(recode(.x,
              "A lot"=4,
              "Some"=3,
              "Not at all"=2,
              "Don't Know / Doesn't Relate to Me" = NULL,
            )))

joined <- joined %>% mutate_at(vars(65:67,79:81,87:89,97:99,107:109,121:123,134:136,153:155,163:165), #re-code stk ratings - adapt
            ~as.numeric(recode(.x,
              "Full Implementation (4)"=4,
              "Partial Implementation (3)"=3,
              "Limited Implementation (2)"=2,
              "No Implementation (1)" = 1,
              "Not Applicable" = NULL
            )))

joined <- joined %>% mutate_at(vars(68:70,82:84,90:92,100:102,110:112,124:126,137:139,156:158,166:168), #re-code stk ratings - access
            ~as.numeric(recode(.x,
              "Full Access (4)"=4,
              "Partial Partial (3)"=3,
              "Limited Access (2)"=2,
              "No Access (1)" = 1,
              "Not Applicable" = NULL
            )))

joined <- joined %>% mutate_at(vars(172:225), #re-code fam ratings
            ~as.numeric(recode(.x,
              "A lot"=4,
              "Some"=3,
              "Not at all"=2,
              "Don't Know / Doesn't Relate to Me" = NULL,
            )))


# MERGE SQIs across roles

joined <- joined %>% mutate(s1.1 = coalesce(S1.1Y,S1.1S,S1.1F))
joined <- joined %>% mutate(s1.2 = coalesce(S1.2Y,S1.2S,S1.2F))
joined <- joined %>% mutate(s1.3 = coalesce(S1.3Y,S1.3S,S1.3F))
joined <- joined %>% mutate(s1.4 = coalesce(S1.4Y,S1.4S,S1.4F))

joined <- joined %>% mutate(s2.1 = coalesce(S2.1Y,S2.1S,S2.1F))
joined <- joined %>% mutate(s2.2 = coalesce(S2.1Y,S2.1S,S2.1F))
joined <- joined %>% mutate(s2.3 = coalesce(S2.2Y,S2.2S,S2.2F))
joined <- joined %>% mutate(s2.4 = coalesce(S2.3Y,S2.3S,S2.3F))
joined <- joined %>% mutate(s2.5 = coalesce(S2.4Y,S2.4S,S2.4F))
joined <- joined %>% mutate(s2.5 = coalesce(S2.5Y,S2.5S,S2.5F))
joined <- joined %>% mutate(s2.6 = coalesce(S2.6Y,S2.6S,S2.6F))
joined <- joined %>% mutate(s2.7 = coalesce(S2.7Y,S2.7S,S2.7F))
joined <- joined %>% mutate(s2.8 = coalesce(S2.8Y,S2.8S,S2.8F))

joined <- joined %>% mutate(s3.1 = coalesce(S3.1Y,S3.1S,S3.1F))
joined <- joined %>% mutate(s3.2 = coalesce(S3.2Y,S3.2S,S3.2F))

joined <- joined %>% mutate(s4.1 = coalesce(S4.1Y,S4.1S,S4.1F))
joined <- joined %>% mutate(s4.2 = coalesce(S4.2Y,S4.2S,S4.2F))
joined <- joined %>% mutate(s4.3 = coalesce(S4.3Y,S4.3S,S4.3F))
joined <- joined %>% mutate(s4.4 = coalesce(S4.4Y,S4.4S,S4.4F))

joined <- joined %>% mutate(s5.1 = coalesce(S5.1Y,S5.1S,S5.1F))
joined <- joined %>% mutate(s5.2 = coalesce(S5.2Y,S5.2S,S5.2F))
joined <- joined %>% mutate(s5.3 = coalesce(S5.3Y,S5.3S,S5.3F))
joined <- joined %>% mutate(s5.4 = coalesce(S5.4Y,S5.4S,S5.4F))

joined <- joined %>% mutate(s6.1 = coalesce(S6.1Y,S6.1S,S6.1F))
joined <- joined %>% mutate(s6.2 = coalesce(S6.2Y,S6.2S,S6.2F))
joined <- joined %>% mutate(s6.3 = coalesce(S6.3Y,S6.3S,S6.3F))
joined <- joined %>% mutate(s6.4 = coalesce(S6.4Y,S6.4S,S6.4F))
joined <- joined %>% mutate(s6.5 = coalesce(S6.5Y,S6.5S,S6.5F))
joined <- joined %>% mutate(s6.6 = coalesce(S6.6Y,S6.6S,S6.6F))
joined <- joined %>% mutate(s6.7 = coalesce(S6.7Y,S6.7S,S6.7F))
joined <- joined %>% mutate(s6.8 = coalesce(S6.8Y,S6.8S,S6.8F))

joined <- joined %>% mutate(s7.1 = coalesce(S7.1Y,S7.1S,S7.1F))
joined <- joined %>% mutate(s7.2 = coalesce(S7.2Y,S7.2S,S7.2F))
joined <- joined %>% mutate(s7.3 = coalesce(S7.3Y,S7.3S,S7.3F))
joined <- joined %>% mutate(s7.4 = coalesce(S7.4Y,S7.4S,S7.4F))
joined <- joined %>% mutate(s7.5 = coalesce(S7.5Y,S7.5S,S7.5F))
joined <- joined %>% mutate(s7.6 = coalesce(S7.6Y,S7.6S,S7.6F))
joined <- joined %>% mutate(s7.7 = coalesce(S7.7Y,S7.7S,S7.7F))

joined <- joined %>% mutate(s8.1 = coalesce(S8.1Y,S8.1S,S8.1F))
joined <- joined %>% mutate(s8.2 = coalesce(S8.2Y,S8.2S,S8.2F))
joined <- joined %>% mutate(s8.3 = coalesce(S8.3Y,S8.3S,S8.3F))
joined <- joined %>% mutate(s8.4 = coalesce(S8.4Y,S8.4S,S8.4F))
joined <- joined %>% mutate(s8.5 = coalesce(S8.5Y,S8.5S,S8.5F))
joined <- joined %>% mutate(s8.6 = coalesce(S8.6Y,S8.6S,S8.6F))
joined <- joined %>% mutate(s8.7 = coalesce(S8.7Y,S8.7S,S8.7F))
joined <- joined %>% mutate(s8.8 = coalesce(S8.8Y,S8.8S,S8.8F))
joined <- joined %>% mutate(s8.9 = coalesce(S8.9Y,S8.9S,S8.9F))
joined <- joined %>% mutate(s8.10 = coalesce(S8.10Y,S8.10S,S8.10F))
joined <- joined %>% mutate(s8.11 = coalesce(S8.11Y,S8.11S,S8.11F))
joined <- joined %>% mutate(s8.12 = coalesce(S8.12Y,S8.12S,S8.12F))
joined <- joined %>% mutate(s8.13 = coalesce(S8.13Y,S8.13S,S8.13F))

joined <- joined %>% mutate(s9.1 = coalesce(S9.1Y,S9.1S,S9.1F))
joined <- joined %>% mutate(s9.2 = coalesce(S9.2Y,S9.2S,S9.2F))
joined <- joined %>% mutate(s9.3 = coalesce(S9.3Y,S9.3S,S9.3F))
joined <- joined %>% mutate(s9.4 = coalesce(S9.4Y,S9.4S,S9.4F))

```