---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(lavaan)
library(polycor)
library(psych)
library(corrplot)
library(tidyverse)
```


```{r}
# subsets
SQIOnly <- joined %>% select(c(s1.1,s1.2,s1.3,s1.4,
                                   s2.1,s2.2,s2.3,s2.4,s2.5,s2.6,s2.7,s2.8,
                                   s3.1,s3.1,
                                   s4.1,s4.2,s4.3,s4.4,
                                   s5.1,s5.2,s5.3,s5.4,
                                   s6.1,s6.2,s6.3,s6.4,s6.5,s6.6,s6.7,s6.8,
                                   s7.1,s7.2,s7.3,s7.4,s7.5,s7.6,s7.7,
                                   s8.1,s8.2,s8.3,s8.4,s8.5,s8.6,s8.6,s8.7,s8.8,s8.9,s8.10,s8.11,s8.12,s8.13,
                                   s9.1,s9.2,s9.3,s9.4))

SQIOnlyYouth <- joined %>% filter (role == "I'm a Young Person")

SQIOnlyYouth <- SQIOnlyYouth %>% select(c(S1.1Y,S1.2Y,S1.3Y,S1.4Y,
                                    S2.1Y,S2.2Y,S2.3Y,S2.4Y,S2.5Y,S2.6Y,S2.7Y,
                                    S3.1Y,S3.2Y,
                                    S4.1Y,S4.2Y,S4.3Y,S4.4Y,
                                    S5.1Y,S5.2Y,S5.3Y,S5.4Y,
                                    S6.1Y,S6.2Y,S6.3Y,S6.4Y,S6.5Y,S6.6Y,S6.7Y,S6.8Y,
                                    S7.1Y,S7.2Y,S7.3Y,S7.4Y,S7.5Y,S7.6Y,S7.7Y,
                                    S8.1Y,S8.2Y,S8.3Y,S8.4Y,S8.5Y,S8.6Y,
                                    S8.7Y,S8.8Y,S8.9Y,S8.10Y,S8.11Y,S8.12Y,S8.13Y,
                                    S9.1Y,S9.2Y,S9.3Y,S9.4Y))

SQIOnlySTK <- joined %>% filter (role == "I'm a Transition Stakeholder")

SQIOnlySTK <- SQIOnlySTK %>% select(c(S1.1Y,S1.2Y,S1.3Y,S1.4Y,
                                    S2.1Y,S2.2Y,S2.3Y,S2.4Y,S2.5Y,S2.6Y,S2.7Y,
                                    S3.1Y,S3.2Y,
                                    S4.1Y,S4.2Y,S4.3Y,S4.4Y,
                                    S5.1Y,S5.2Y,S5.3Y,S5.4Y,
                                    S6.1Y,S6.2Y,S6.3Y,S6.4Y,S6.5Y,S6.6Y,S6.7Y,S6.8Y,
                                    S7.1Y,S7.2Y,S7.3Y,S7.4Y,S7.5Y,S7.6Y,S7.7Y,
                                    S8.1Y,S8.2Y,S8.3Y,S8.4Y,S8.5Y,S8.6Y,
                                    S8.7Y,S8.8Y,S8.9Y,S8.10Y,S8.11Y,S8.12Y,S8.13Y,
                                    S9.1Y,S9.2Y,S9.3Y,S9.4Y))

SQIOnlyFAM <- joined %>% filter (role == "I'm a Parent / Legal Guardian")

SQIOnlyFAM <- SQIOnlyFAM %>% select(c(S1.1Y,S1.2Y,S1.3Y,S1.4Y,
                                    S2.1Y,S2.2Y,S2.3Y,S2.4Y,S2.5Y,S2.6Y,S2.7Y,
                                    S3.1Y,S3.2Y,
                                    S4.1Y,S4.2Y,S4.3Y,S4.4Y,
                                    S5.1Y,S5.2Y,S5.3Y,S5.4Y,
                                    S6.1Y,S6.2Y,S6.3Y,S6.4Y,S6.5Y,S6.6Y,S6.7Y,S6.8Y,
                                    S7.1Y,S7.2Y,S7.3Y,S7.4Y,S7.5Y,S7.6Y,S7.7Y,
                                    S8.1Y,S8.2Y,S8.3Y,S8.4Y,S8.5Y,S8.6Y,
                                    S8.7Y,S8.8Y,S8.9Y,S8.10Y,S8.11Y,S8.12Y,S8.13Y,
                                    S9.1Y,S9.2Y,S9.3Y,S9.4Y))


SQIyouthdevelopment <-joined %>% select(c(s2.1,s2.2,s2.3,s2.4,s2.5,s2.6,s2.7,s2.8))

SQIemployment <- joined %>% select(c(s8.1,s8.2,s8.3,s8.4,s8.5,s8.6,s8.6,s8.7,s8.8,s8.9,s8.10,s8.11,s8.12,s8.13))

SQIfamilyEngagement <- joined %>% select(c(s4.1,s4.2,s4.3,s4.4))

SQIthreedomain <- joined %>% select(c(s2.1,s2.2,s2.3,s2.4,s2.5,s2.6,s2.7,s2.8,
                                      s4.1,s4.2,s4.3,s4.4,
                                      s8.1,s8.2,s8.3,s8.4,s8.5,s8.6,s8.6,s8.7,s8.8,s8.9,s8.10,s8.11,s8.12,s8.13))


```

```{r}
# make an item key for reference going forward.

itemkey = data.table(
  SQIs = c("Career Exploration Planning and Preparation 1.1",
           "Postsecondary and College Planning 1.2",
           "Independent/Community Living 1.3",
           "Significant Role of School Personnel 1.4",
           "Self-Awareness 2.1",
           "Disability Awareness 2.2",
           "Independent Living Skill Development 2.3",
           "Self-Determination Skill Development 2.4",
           "Self-Management Skill Development 2.5",
           "Leadership Skill Development 2.6",
           "Youth Engagement in Transition 2.7",
           "Significant Role of Adult 2.8",
           "Authentic Person and Family Centered Planning Practices 3.1",
           "Person and Family Centered Program Design 3.2",
           "Family Engagement in Transition Planning 4.1",
           "Family Information Sharing Activities 4.2",
           "Peer to Peer Family Support 4.3",
           "Family Respite 4.4",
           "Friendship 5.1",
           "Sense of Belonging 5.2",
           "Social Skills Development 5.3",
           "Anti-Bullying Efforts 5.4",
           "Independent Living Skills Development 6.1",
           "Planning for Future Living Arrangements 6.2",
           "Travel and Transportation Skills 6.3",
           "Recreation and Leisure 6.4",
           "Community Based Experiences 6.5",
           "Faith Based Experiences 6.6",
           "Civic Engagement 6.7",
           "Mental Health Supports 6.8",
           "Agencies in Schools 7.1",
           "Transition Coordinating Councils 7.2",
           "Community Agency Nights about Employment 7.3",
           "Transition Staffings 7.4",
           "Employment Expos 7.5",
           "Transition Fairs 7.6",
           "Transition Conferences 7.7",
           "Career Development Classes 8.1",
           "Career Clubs 8.2",
           "Career and Technical Education 8.3",
           "Career Exploration 8.4",
           "Discovery Process 8.5",
           "Unpaid Work Experience 8.6",
           "Paid Work Experience 8.7",
           "OVR Services 8.8",
           "Job Coaching Services 8.9",
           "Summer Employment 8.10",
           "On-the-Job Training 8.11",
           "Employer Partnerships 8.12",
           "University Partnerships 8.13",
           "Pre-College Experience Programs 9.1",
           "College-Based Transition Programs 9.2",
           "Postsecondary Education Programs 9.3",
           "Postsecondary Career Training Programs 9.4"
           ))

```

```{r}

# Inter-Item Correlations:

# Youth Dev
youthdevpoly <- polychoric(SQIyouthdevelopment,smooth=TRUE,global = TRUE,na.rm = TRUE, delete = TRUE)
print(youthdevpoly$rho)
corrplot(youthdevpoly$rho,type="lower",method="number")

# Employment
employmentpoly <-polychoric(SQIemployment,smooth=TRUE,global = TRUE,na.rm = TRUE, delete = TRUE)
print(employmentpoly$rho)
corrplot(employmentpoly$rho,type="lower",method="number")

# Family Engagement
familyengagementploy <- polychoric(SQIfamilyEngagement,smooth=TRUE,global = TRUE,na.rm = TRUE, delete = TRUE)
print(familyengagementploy$rho)
corrplot(familyengagementploy$rho,type="lower",method="number")

# Three domains combined
threedomainploy <- polychoric(SQIthreedomain,smooth=TRUE,global = TRUE,na.rm = TRUE, delete = TRUE)
print(threedomainploy$rho)
corrplot(threedomainploy$rho,type="lower",method="number")

# three domains w/ CFIRs


KMO(threedomainploy$rho)
cortest.bartlett(threedomainploy$rho,n=1997)

```
